### ISSUE TITLE
Is there any open code about CLIP

### ISSUE THREAD

**Issue by laiyingxin2** [talreiss/FACTOR#1]

**Comment by talreiss** [comment]
Hi,

Our plan is to release the text-to-image code soon as well. We'll update the repository when it's ready to be released.

**Comment by talreiss** [comment]
Hi, 

The code will not be released at this time because of our lack of time, and the fact that it is not a priority code release. Please note that CLIP is used in a straightforward way without any tricks, so you can easily implement it on your own. I apologize for that, but hopefully I'll be able to get it done soon.

Tal
